version: 0.0
os: linux
files:
  - source: public/index.php
    destination: /var/www/html/
permissions:
  - object: /var/www/html
    pattern: "**"
    type:
      - directory
      - file
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

